# Generated by Django 5.1 on 2024-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uppcomingcar_delete_upcomingcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('car_image', models.ImageField(upload_to='car_images/')),
            ],
        ),
    ]
