# Generated by Django 5.1 on 2024-08-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
