# Generated by Django 5.1 on 2024-09-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_car_price_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcar',
            name='battery_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='driving_range',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='ex_showroom_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='individual_registration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featuredcar',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Electric', 'Electric')], default='', max_length=50),
        ),
    ]
