# Generated by Django 5.1 on 2024-09-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_featuredcar_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcar',
            name='battery_capacity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='driving_range',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
