# Generated by Django 5.1 on 2024-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_featuredcar_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcar',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
