# Generated by Django 5.1 on 2024-09-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_featuredcar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcar',
            name='ex_showroom_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='individual_registration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='insurance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='other_charges',
            field=models.CharField(default='', max_length=50),
        ),
    ]
