# Generated by Django 5.1 on 2024-09-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_featuredcar_ex_showroom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcar',
            name='battery_capacity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='driving_range',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='ex_showroom_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='individual_registration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='insurance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='mileage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='other_charges',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Electric', 'Electric')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='battery_capacity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='driving_range',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='ex_showroom_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='individual_registration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='insurance',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='mileage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='other_charges',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uppcomingcar',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Electric', 'Electric')], default='', max_length=50),
        ),
    ]
