# Generated by Django 5.1 on 2024-09-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_featuredcarreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcar',
            name='car_type',
            field=models.CharField(default='featured', max_length=80),
        ),
        migrations.AddField(
            model_name='popularcar',
            name='car_type',
            field=models.CharField(default='popular', max_length=80),
        ),
    ]
